### ISSUE TITLE
Get "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by godfreycgs** [substack/virtual-dom-starter#4]
When I opened the example webpage, and clicked the "click me" button,
the clicked times didn't change, instead I got the browser console error: **Uncaught RangeError: Maximum call stack size exceeded**

Here is my enviroment:
```
node: v0.12.7
browser: chrome 43.0.2357.134 (64-bit)
```

**Comment by alessioalex** [comment]
`main-loop` seems to be the broken thing in this: https://github.com/Raynos/main-loop/issues/21

**Comment by yoshuawuyts** [comment]
`main-loop` hasn't changed lately, it appears it's something in [`virtual-dom/patch`](https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/patch.js).

<img width="529" alt="screen shot 2015-07-28 at 23 12 13" src="https://cloud.githubusercontent.com/assets/2467194/8932118/552fdb00-357e-11e5-8f84-0eb699f51b21.png">

**Comment by substack** [comment]
pegged at 2.0.1 until the issue is fixed upstream

**Comment by substack** [comment]
virtual-dom was fixed upstream
